### ISSUE TITLE
[vite:asset-import-meta-url] `new URL(url, import.meta.url)` is not supported in SSR.

### ISSUE THREAD

**Issue by netopolit** [antfu/vite-ssg#199]
I am trying to pass image name to a child component and use it to create an URL to use as a background image on HTML element.
My approach was passing image name as a prop imgName to a component. In the receiving component I'm doing this:

```
<script>
  props: {
    imgName: {
      type: String,
      required: true,
    },
  },

  data() {
    return {
       imgUrl: "",
    }
  },
  
  created() {
    this.imgUrl = `url(${new URL(`../assets/images/${this.imgName}`, import.meta.url).href})`
  },
</script>

<style>
  .element {
    ...
    background-image: v-bind(imgUrl);
    ...
}
</style>
```
This approach works in dev environment  but when creating a production bundle I get this error [vite-plugin-pwa] `new URL(url, import.meta.url)` is not supported in SSR.

Any idea how I can generate image URL that will work both on the dev server and for production bundle using SSR?

Thank you.

**Comment by userquin** [comment]
@netopolit try  `mounted` instead

**Comment by netopolit** [comment]
> @netopolit try `mounted` instead `created`

I still get the same error on running `pnpm run build`

**Comment by userquin** [comment]
@netopolit if you're using the `assets` directory all asset names will include the hash since vite will transform them: maybe you can move them to public directory or to a custom directory inside assets folder, then you can use `import.meta.glob/globEager` in a custom module and them map the key and the url (like the `src/modules/i18n.ts` module on vitesse) or add a virtual module to resolve them using for example `fast-glob`.

**Comment by userquin** [comment]
@netopolit reviwing the vite docs, `import.meta.url` is not supported, does not work with SSR, see last warning on the following entry: https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url
