### ISSUE TITLE
Any concerns while using with Suspense

### ISSUE THREAD

**Issue by husayt** [antfu/vite-ssg#36]
What are the things to consider if using SSG with Suspense?

Thanks

**Comment by userquin** [comment]
There is nothing to consider ;), the problem is that the `suspense` keeps changing ...

You can see an example in `vite plugin pwa` that I included a few months ago in a test, but it is in a branch that will be removed soon.

The example is [here](https://github.com/antfu/vite-plugin-pwa/blob/sw-networkfirst/examples/vue-router/src/App.vue)

**Comment by antfu** [comment]
I didn't try it. But I don't think there is anything we need to handle specially. Open an issue when you really find any bug. Thanks.
