### ISSUE TITLE
support custom vite config location

### ISSUE THREAD

**Issue by LiuJiangshan** [antfu/vite-ssg#57]
`
vite-ssg build -c custom.vite.config.ts
`

**Comment by antfu** [comment]
Emm why? This is actually handed by vite itself not us.

**Comment by gilesbutler** [comment]
Hey, I'm having the same issue. 

I'd like to pass a custom config through to vite as we have different build configs for that specific scripts run for different apps and environments.

I thought `vite-ssg --config vite.publish.config.js` would use `vite.publish.config.js` instead of `vite.config.js`.

Thanks
